spark.master                     spark://spark-master:7077
spark.jars.packages              org.mongodb.spark:mongo-spark-connector_2.12:10.7.0
spark.mongodb.read.connection.uri mongodb://mongodb:27017/projectbd
spark.mongodb.write.connection.uri mongodb://mongodb:27017/projectbd
spark.executor.memory            512m
spark.driver.memory              512m
spark.driver.host                spark-master
spark.driver.bindAddress         0.0.0.0
spark.executor.cores             1
spark.sql.shuffle.partitions     8
spark.ui.showConsoleProgress     false
